version: "3.9"
services:
  mariadb-1:
    image: alejandrodu/mariadb-primary
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mariadb-1-data:/var/lib/mysql
      - ${PWD}/files:/root

  mariadb-2:
    image: alejandrodu/mariadb-replica
    environment:
      MARIADB_PRIMARY_HOST: 192.168.1.181
      MARIADB_PRIMARY_PORT: 3306
    ports:
      - "3307:3306"
    volumes:
      - ${PWD}/mariadb-2-data:/var/lib/mysql
      - ${PWD}/files:/root

  mariadb-3:
    image: alejandrodu/mariadb-replica
    environment:
      MARIADB_PRIMARY_HOST: 192.168.1.181
      MARIADB_PRIMARY_PORT: 3306
    ports:
      - "3308:3306"
    volumes:
      - ${PWD}/mariadb-3-data:/var/lib/mysql
      - ${PWD}/files:/root

  maxscale:
    image: alejandrodu/mariadb-maxscale
    command: --admin_host 0.0.0.0 --admin_secure_gui false
    depends_on:
      - primary
      - replica1
      - replica2
    ports:
      - "4000:4000"
      - "8989:8989"
      - "27017:27017"
    volumes:
      - ${PWD}/maxscale-data:/var/lib/maxscale
    environment:
      MARIADB_PRIMARY_HOST: 10.42.0.238
      MARIADB_PRIMARY_PORT: 3306
