version: '3.8'
services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "3G"   # Increased from 1G to 3G since you have 4GB
      VERSION: "1.20.4"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "3G"
    deploy:
      resources:
        limits:
          memory: 3.5G # Leave 500MB for the OS
      placement:
        constraints: [node.role == manager]
    volumes:
      - mc_data:/data

volumes:
  mc_data: