version: '3.8'
services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "1G"   # Adjust based on your RAM (1.5GB total on OPZ3)
      VERSION: "1.20.4"
      ONLINE_MODE: "FALSE" # Set to TRUE if you have a paid account
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - mc_data:/data

volumes:
  mc_data: